language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y php5
install: pip install tox-travis
script: tox
notification:
    email: false
